version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 481516
      POSTGRES_DB: wb_l0
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nats:
    image: nats-streaming:latest
    container_name: my_nats
    ports:
      - "4222:4222"

  my_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_service
    depends_on:
      - postgres
      - nats
    ports:
      - "8080:8080"

volumes:
  postgres_data:
